name: "Playwright CI/CD Pipeline"

on:
  push:
    branches:
      - main # Führen Sie die Pipeline nur bei Änderungen im Branch "main" aus
  pull_request:
    branches:
      - main

jobs:
  test-playwright:
    name: Run Playwright Tests
    runs-on: windows-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js einrichten
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: npm ci

      # 4. Playwright installieren
      - name: Install Playwright
        run: npx playwright install --with-deps

      # 5. Tests ausführen
      - name: Run Playwright Tests
        run: npx playwright test

      # 6. Testergebnisse hochladen
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: test-results