name: "Playwright CI/CD Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-playwright:
    name: Run Playwright Tests
    runs-on: windows-latest

    permissions: # added permissions
      contents: read
      actions: write


    env: # Dbugging aktivieren
      ACTIONS_SETP_DEBUG: true

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js einrichten
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: npm ci


      # 4. API-Server starten
      - name: Start API Server
        run: |
          cd C:\Users\azebaze\PycharmProjects\PythonProject
          python API_Neu.py &
        shell: powershell


      # 5. Warten, bis die API verfügbar ist
      - name: Wait for API
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:8001 && break || sleep 5;
          done
        shell: bash

      # 5. Projekt bauen
      #- name: Build project
       # run: npm run build


      # 6. Playwright installieren
      - name: Install Playwright
        run: npx playwright install --with-deps

      # 7. Tests ausführen
      - name: Run Playwright Tests
        run: |
          mkdir -p test-results
          npx playwright test --output test-results

      # 8. Testergebnisse hochladen
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results